services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./dockerfiles
      dockerfile: apigateway.dockerfile
    ports:
      - "80:80" # TPC port for API Gateway
    env_file: 
      - .env
  inventory-service:
    container_name: inventory-service
    build:
      context: ./dockerfiles
      dockerfile: inventory.dockerfile
    ports:
      - "5000:5000"  # gRPC service for inventory
    env_file: 
      - .env
    depends_on:
      - postgres

  kitchen-service:
    container_name: kitchen-service
    build:
      context: ./dockerfiles
      dockerfile: kitchen.dockerfile
    ports:
      - "5001:5000"  # gRPC service for kitchen
    env_file:
      - .env
    depends_on:
      - postgres

  orders-service:
    container_name: orders-service
    build:
      context: ./dockerfiles
      dockerfile: orders.dockerfile
    ports:
      - "5002:5000"  # gRPC service for orders
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build:
      context: ./dockerfiles
      dockerfile: database.dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
